name: LumiAIO Automation

on:
  schedule:
    # Tous les jours à 23h (UTC)
    - cron: '0 23 * * *'
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run LumiAIO Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python lumiaio-gen.py
